### ISSUE TITLE
sti build hangs

### ISSUE THREAD

**Issue by iocanel** [openshift/source-to-image#149] opened 2015-02-27 20:21 UTC
I am using sti from the command line and in most cases, I notice that it "hungs".

When I am using log level 3 I see that the build output always hungs at exactly the same line.

What is strange though is that when I check the docker logs, I can see that the assemble script has successfully finished and also that the container has exited gracefully. The target image of course is never created.

The last couple of days I've made so many attempts and only two of them were successful (I haven't done anything different).

**Comment by bparees** [comment] 2015-02-27 20:27
Can you give us steps to recreate?  what STI image, what STI scripts, what commit level of STI, etc?

(also what docker version)

**Comment by iocanel** [comment] 2015-02-27 20:37
I've been using the https://github.com/fabric8io/base-sti base image. The sti scripts are part of the image and they are referenced using their github url. 

My docker is at 1.4.1 and I'll try to upgrade and see if it makes any difference.

Here's an example of how I use the command:

sti build https://github.com/fabric8io/example-camel-cdi.git fabric8/base-sti fabric8/camel-example --loglevel=3

**Comment by bparees** [comment] 2015-02-27 20:52
yup, I was able to reproduce this just running your sti command.  and I do see the container has exited after running assemble successfully.

Given that the sti output hangs partway through the assemble script output, i'm guessing we're screwing up/overfilling a buffer somewhere.  @soltysh can you take a look?

**Comment by iocanel** [comment] 2015-02-27 20:53
The behaviour that I see makes me feel that the issue is related with the readers of the containers output and error. It seems like on of them stops reading and fails to close preventing the method to return? (limited understanding of golang here).

**Comment by bparees** [comment] 2015-02-27 20:54
in the meantime, could you edit your assemble script to redirect the maven output to /dev/null?  that might let you make progress...

**Comment by iocanel** [comment] 2015-02-28 03:55
It does seem to make a difference.

**Comment by soltysh** [comment] 2015-03-02 10:45
Looking...

**Comment by iocanel** [comment] 2015-03-13 15:55
Using the latest master, I still have the same issue.

**Comment by soltysh** [comment] 2015-03-16 15:09
@iocanel can you please check this once more. I just did a fresh build of STI ([this revision](https://github.com/openshift/source-to-image/commit/aded45154b8b3bd2297d7643bde6176b4d71f01f)) and the command:
```
sti build https://github.com/fabric8io/example-camel-cdi.git fabric8/base-sti fabric8/camel-example --loglevel=3
```
worked without any problem resulting in `fabric8/camel-example` image. The only problem I hit was running that result image ended in:
```
$ docker run fabric8/camel-example
/tmp/scripts/run: line 3: deploy-and-start: command not found
```
But that is not a STI problem from what I see. If you're still hitting the problem, please include the entire output of the build here (with `--loglevel=5`), I'll try to have a closer look at it.

**Comment by iocanel** [comment] 2015-03-16 15:17
Will check and get back to you.

**Comment by goldmann** [comment] 2015-03-17 14:08
I'm seeing this too. It feels like the build is stuck on downloading some Maven artifacts in my case, but in fact, the build container already exited with status `0` and new image was created as it should. My example command is:

```
$ sti build --loglevel=5 --forcePull=false https://github.com/goldmann/openshift-examples --contextDir=spring-eap6-quickstart 8fffd6ce363a test-jee-app
```

Where the `8fffd6ce363a` image is a custom EAP image, but probably the `wildfly8-centos` image could be used too.

One note: this does not happen every time. If I re-run the command, there is a high chance that I'll get the full output.

**Comment by goldmann** [comment] 2015-03-26 14:44
Any news on this? Since we added STI to our CI this is now failing our builds.

**Comment by mfojtik** [comment] 2015-03-26 14:55
https://github.com/openshift/source-to-image/pull/160

@goldmann this might fix you (--assebleOutput=false)

**Comment by goldmann** [comment] 2015-03-26 14:57
@mfojtik Well, this is more like a workaround :) Is there a way to redirect the output to somewhere. We would still need the logs for further investigation.

**Comment by soltysh** [comment] 2015-03-26 15:45
@goldmann sorry but I can't still reproduce it and I'm still investigating the the source of the problem.

**Comment by goldmann** [comment] 2015-03-26 16:46
@soltysh Fair enough, update this issues if you have something. Thanks!

**Comment by bparees** [comment] 2015-05-18 13:54
@goldmann still an issue?

**Comment by goldmann** [comment] 2015-05-18 13:56
Haven't seen it in a while.

**Comment by bparees** [comment] 2015-05-18 14:13
closing, feel free to reopen if it recurs.

**Closed by bparees** 2015-05-18 14:13 UTC

**Comment by goldmann** [comment] 2015-05-18 18:03
After we upgraded to ac0b2512c9f933afa985b056a7f3cbce1942cacb, there is no output **at all** on our CI and the STI process is waiting (hanging) forever for the container, which exited cleanly.

Last lines of the container log:

```
Downloading: https://maven.repository.redhat.com/techpreview/all/org/apache/apache/7/apache-7.pom
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/apache/apache/7/apache-7.pom
[WARNING] Checksum validation failed, no checksums available from the repository for https://repository.jboss.org/nexus/content/groups/public/org/apache/apache/7/apache-7.pom
Downloaded: https://repository.jboss.org/nexus/content/groups/public/org/apache/apache/7/apache-7.pom (15 KB at 7.4 KB/sec)
Downloading: https://maven.repository.redhat.com/techpreview/all/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar
Downloading: https://repository.jboss.org/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar
[WARNING] Checksum validation failed, no checksums available from the repository for https://repository.jboss.org/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar
Downloaded: https://repository.jboss.org/nexus/content/groups/public/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.jar (23 KB at 13.5 KB/sec)
[INFO] 
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ spring-eap6-quickstart ---
[INFO] Deleting /home/jboss/source/target
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.249s
[INFO] Finished at: Mon May 18 14:02:34 EDT 2015
[INFO] Final Memory: 17M/903M
[INFO] ------------------------------------------------------------------------
Copying all WAR and EAR artifacts from /home/jboss/source/deployments directory into /opt/eap/standalone/deployments for later deployment...
'/home/jboss/source/deployments/ROOT.war' -> '/opt/eap/standalone/deployments/ROOT.war'
```

**Comment by mfojtik** [comment] 2015-05-18 18:13
@goldmann is https://github.com/openshift/source-to-image/issues/149#issuecomment-82372044 still a reproducer for this?

**Comment by goldmann** [comment] 2015-05-19 06:11
Just to let all know - we talked with @mfojtik and the issue is probably with the goroutines and wait when reading the container output.
