### ISSUE TITLE
s2i v1.1.2 fail connect on MacOS

### ISSUE THREAD

**Issue by luiscoms** [openshift/source-to-image#597] opened 2016-09-28 19:41 UTC
When I build an image on MacOS I get the following error:

```
I0928 16:24:47.530975     951 docker.go:306] Connecting to docker on tcp://192.168.99.100:2376
FATAL: Unable to connect to Docker daemon. Please set the DOCKER_HOST or make sure the Docker socket "tcp://192.168.99.100:2376" exists
Running S2I version "v1.1.2"
I0928 16:24:47.548775     952 docker.go:306] Connecting to docker on tcp://192.168.99.100:2376
Checking if image "s2i-java8-maven-candidate" is available locally ...

Error describing image:		unable to get metadata for s2i-java8-maven-candidate:latest
Source:				file:///Users/luiscoms/LCS/github/s2i-java/1.8-maven/test/test-app
Output Image Tag:		s2i-java8-maven-candidate-test-app
Environment:
Incremental Build:		enabled
Incremental Image Pull User:
Remove Old Build:		disabled
Builder Pull Policy:		never
Previous Image Pull Policy:	if-not-present
Quiet:				disabled
Layered Build:			disabled
Docker Endpoint:		tcp://192.168.99.100:2376
Docker Pull Config:		/Users/luiscoms/.docker/config.json
Docker Pull User:

I0928 16:24:47.551368     952 docker.go:306] Connecting to docker on tcp://192.168.99.100:2376
FATAL: Unable to connect to Docker daemon. Please set the DOCKER_HOST or make sure the Docker socket "tcp://192.168.99.100:2376" exists
S2I image 's2i-java8-maven-candidate' test FAILED (exit code: 1)
```

**Comment by bparees** [comment] 2016-09-28 20:45
is docker running at 192.168.99.100:2376 ?

**Comment by csrwng** [comment] 2016-09-28 20:49
This is a bug with the Docker engine client. If no DOCKER_HOST is configured on the Mac, it defaults to {host}:2376 instead of /var/run/docker.socket. We need a workaround like the one I have for cluster up:
https://github.com/openshift/origin/blob/master/pkg/bootstrap/docker/up.go#L419-L426

**Comment by bparees** [comment] 2016-10-09 23:44
Seems like a dupe of https://github.com/openshift/source-to-image/issues/603

@jim-minter fyi.

**Closed by bparees** 2016-10-09 23:44 UTC
