### ISSUE TITLE
Implement incremental builds with runtime image

### ISSUE THREAD

**Issue by burdiyan** [openshift/source-to-image#819] opened 2017-10-18 15:20 UTC
Right now s2i does not allow to use incremental build when using runtime images and throws the following error: `ERROR: Incremental build with runtime image isn't supported`.

I would like to know what is the reason of disallowing that (whether there is some technical implications or just lack of time to implement and test it).

I always use a runtime image, event for dynamic languages (my builder images have a lot of stuff I don't need at runtime, like more convenient shells, git and etc.).

The lack of incremental builds in this situation make my builds super slow. The only workaround I can do right now is mounting a volume inside a build container and store artefacts there, which are reusing in the subsequent builds. Although that is not ideal for various reasons.

**Comment by bparees** [comment] 2017-10-18 15:33
dupe of https://github.com/openshift/source-to-image/issues/738, see response there for another workaround.

**Closed by bparees** 2017-10-18 15:33 UTC
