### ISSUE TITLE
nginx-app does not follow the standard directory structure for a s2i application

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/source-to-image#508] opened 2016-05-24 21:17 UTC
https://github.com/openshift/source-to-image/tree/master/examples/nginx-app does not follow the standard directory structure for a s2i application i.e. the structure gets created with `s2i create <image name> <destination directory>` 

```
── Dockerfile
├── Makefile
├── .s2i
│   └── bin
│       ├── assemble
│       ├── run
│       ├── save-artifacts
│       └── usage
└── test
    ├── run
    └── test-app
```

**Comment by php-coder** [comment] 2016-05-24 22:10
CC @PI-Victor

**Comment by PI-Victor** [comment] 2016-05-25 20:51
you're correct, it doesn't. it's a feature, not a bug.
this tutorial was made as simple as possible. we've intentionally left parts of this out to make it as a basic boilerplate and showcase "internals" - let's say.
you can see it explained here: https://github.com/openshift/source-to-image/pull/371#issuecomment-160782599 

@bparees should i modify the example to follow the dir structure as mentioned above, or we can close this?

**Comment by bparees** [comment] 2016-05-25 22:50
yeah i don't think it's critical this align with `s2i create`.  if @LalatenduMohanty wants to create a PR to restructure it (including updating the readme/tutorial) i think we'd accept it, but otherwise i don't think we need to do anything here.  hence the p3/help-wanted labels :)

**Comment by LalatenduMohanty** [comment] 2016-05-26 05:15
@bparees that sounds good. I will create the PR as per https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md etc

**Comment by PI-Victor** [comment] 2016-05-26 07:50
sound good to me. @LalatenduMohanty thank you for taking the time :+1:

**Comment by bparees** [comment] 2016-06-09 20:27
@LalatenduMohanty are you still intending to submit a PR?

**Comment by LalatenduMohanty** [comment] 2016-07-25 05:22
@bparees Sorry could not manage to send a PR. I spent some time for it but my understanding of s2i is still not up to mark.  Also when I tried `s2i build test/ nginx-centos7 nginx-app` it failed. Not sure of the cause. Need to look in to the error.  I will try to send the PR this week.

**Comment by luiscoms** [comment] 2016-10-04 00:06
@LalatenduMohanty you can use the image that I create for nginx [here](https://hub.docker.com/r/luiscoms/s2i-nginx/)

**Comment by PI-Victor** [comment] 2016-10-20 09:21
closing this, see my comment here: https://github.com/openshift/source-to-image/pull/602#issuecomment-255054223

**Closed by PI-Victor** 2016-10-20 09:21 UTC
Labels: help-wanted, priority/P3
