### ISSUE TITLE
STI fails when specified image is the ID of the image not the name

### ISSUE THREAD

**Issue by goldmann** [openshift/source-to-image#274] opened 2015-08-24 12:56 UTC
Below log is pretty much self-explaining :)

```
$ sti build --loglevel=5 --force-pull=false --context-dir=spring-eap6-quickstart -E "/tmp/tmpHKWP4H" https://github.com/jboss-openshift/openshift-examples 56b402f12dab integ-56b402f12dab
W0824 13:53:24.822194 27922 main.go:137] Unable to read /tmp/tmpHKWP4H: open /tmp/tmpHKWP4H: no such file or directory

Builder Image:		56b402f12dab
Source:			https://github.com/jboss-openshift/openshift-examples
Context Directory:	spring-eap6-quickstart
Output Image Tag:	integ-56b402f12dab
Environment File:	/tmp/tmpHKWP4H
Incremental Build:	enabled
Remove Old Build:	disabled
Force Pull:		disabled
Quiet:			disabled
Layered Build:		disabled
Docker Endpoint:	unix:///var/run/docker.sock

I0824 13:53:24.916836 27922 docker.go:216] Pulling image 56b402f12dab:latest
I0824 13:53:32.318927 27922 docker.go:219] An error was received from the PullImage call: Error: image library/56b402f12dab:latest not found
E0824 13:53:32.318955 27922 main.go:327] An error occurred: unable to get 56b402f12dab:latest
E0824 13:53:32.318962 27922 main.go:328] Suggested solution: check image name, or if using local image add --force-pull=false flag
I0824 13:53:32.318965 27922 main.go:330] Details: Error: image library/56b402f12dab:latest not found
E0824 13:53:32.318969 27922 main.go:334] If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs.Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using --loglevel=3
```

**Comment by mfojtik** [comment] 2015-08-24 12:59
@goldmann the Go docker client don't know how to get image using the image_id. It parses "56b402f12dab" as image name and since it does not have repository name, it defaults to "library/".

I wonder if there is a call in Go docker client that allow us to search for the Docker image using the image 'id'.

**Comment by bparees** [comment] 2015-10-02 14:45
closing as working as designed.

**Closed by bparees** 2015-10-02 14:45 UTC
