### ISSUE TITLE
filesystem build adds an extra directory

### ISSUE THREAD

**Issue by accursoft** [openshift/source-to-image#363] opened 2015-11-19 13:57 UTC
`s2i build {git repository}` adds the files from the repository to `/tmp/src`. `s2i build some/path` adds the files to `tmp/src/path`.

This makes it tricky to write an `assemble` script which works for sources from both git repos and the local file system.

**Comment by GrahamDumpleton** [comment] 2015-11-25 06:27
Is this related to #348. That is, fixed by it, or caused by it.

**Comment by mfojtik** [comment] 2015-12-15 10:01
@accursoft can you please confirm that this issue was fixed?

**Comment by accursoft** [comment] 2015-12-15 10:54
It's not fixed, and I'm not clear which changeset was supposed to have fixed it.

**Closed** 2015-12-17 14:20 UTC
Labels: area/usability, kind/bug, priority/P3
