### ISSUE TITLE
Error E0715 on Windows 10 / docker for windows / s2i 1.1.0

### ISSUE THREAD

**Issue by arielcarrera** [openshift/source-to-image#544] opened 2016-07-15 23:14 UTC
When you try to build an image, using s2i on Windows 10 and docker for windows, s2i can't remove a temporal folder after the image building.

Environment:
-windows 10
-docker for windows 1.12.0-rc4-beta19 (build: 5465)
-source-to-image-v1.1.0-9350cd1-windows-amd64.zip

Source: custom wildfly imagen (like s2i Wildfly image)

command line: 
s2i build test/test-app/ s2i-wildfly-keycloak openshift-test --loglevel=5 -U http://localhost:2375

C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak>s2i build test/test-app/ s2i-wildfly-keycloak openshift-test --loglevel=5 -U http://localhost:2375
I0715 19:58:22.369129 03124 main.go:62] Running S2I version "v1.0.9"
I0715 19:58:22.390128 03124 docker.go:358] Using locally available image "s2i-wildfly-keycloak:latest"

Builder Name:                   WildFly 10.0.0.Final con adaptador Keycloak 1.9.8.Final
Builder Image:                  s2i-wildfly-keycloak
Builder Image Version:          71d72b4
Builder Base Version:           e178f1c
Source:                         test/test-app/
Output Image Tag:               openshift-test
Environment:
Incremental Build:              disabled
Remove Old Build:               disabled
Builder Pull Policy:            if-not-present
Previous Image Pull Policy:     if-not-present
Quiet:                          disabled
Layered Build:                  disabled
Docker Endpoint:                http://localhost:2375

I0715 19:58:22.466130 03124 docker.go:358] Using locally available image "s2i-wildfly-keycloak:latest"
I0715 19:58:22.502129 03124 docker.go:358] Using locally available image "s2i-wildfly-keycloak:latest"
I0715 19:58:22.505129 03124 docker.go:478] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0715 19:58:22.509129 03124 scm.go:18] DownloadForSource test/test-app/
I0715 19:58:22.517128 03124 git.go:198] useCopy proto spec false local git repo true has git bin true
I0715 19:58:22.523128 03124 git.go:204] makePathAbsolute test/test-app/
I0715 19:58:22.525129 03124 git.go:207] makePathAbsolute new path C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\ err <nil>
I0715 19:58:22.530129 03124 scm.go:25] return from ParseFile file exists true proto specified false use copy false
I0715 19:58:22.535129 03124 scm.go:32] new source from parse file C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\
I0715 19:58:22.544128 03124 git.go:198] useCopy proto spec true local git repo true has git bin true
I0715 19:58:22.550131 03124 git.go:204] makePathAbsolute C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\
I0715 19:58:22.554128 03124 git.go:207] makePathAbsolute new path C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\ err <nil>
I0715 19:58:22.559128 03124 sti.go:142] Preparing to build openshift-test
I0715 19:58:22.567131 03124 git.go:198] useCopy proto spec true local git repo true has git bin true
I0715 19:58:22.572128 03124 git.go:204] makePathAbsolute C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\
I0715 19:58:22.576128 03124 git.go:207] makePathAbsolute new path C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\ err <nil>
I0715 19:58:22.581130 03124 clone.go:32] Downloading "file://C:\\Desarrollo\\workspace_sy\\openshift\\test\\s2i-wildfly-keycloak\\test\\test-app\\" ...
I0715 19:58:22.587127 03124 clone.go:42] Cloning sources into "C:\\Users\\Ariel\\AppData\\Local\\Temp\\s2i679349191\\upload\\src"
I0715 19:58:23.304574 03124 install.go:251] Using "assemble" installed from "image:///usr/libexec/s2i/assemble"
I0715 19:58:23.307571 03124 install.go:251] Using "run" installed from "image:///usr/libexec/s2i/run"
I0715 19:58:23.310573 03124 install.go:251] Using "save-artifacts" installed from "image:///usr/libexec/s2i/save-artifacts"
I0715 19:58:23.316571 03124 ignore.go:58] .s2iignore file does not exist
I0715 19:58:23.318567 03124 sti.go:154] Clean build will be performed
I0715 19:58:23.323572 03124 sti.go:157] Performing source build from file://C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\
I0715 19:58:23.330569 03124 sti.go:168] Running "assemble" in "openshift-test"
I0715 19:58:23.333571 03124 sti.go:440] Using image name s2i-wildfly-keycloak
I0715 19:58:23.339581 03124 sti.go:444] No user environment provided (no environment file found in application sources)
I0715 19:58:23.343578 03124 sti.go:547] starting the source uploading ...
I0715 19:58:23.347583 03124 tar.go:193] Adding "C:\\Users\\Ariel\\AppData\\Local\\Temp\\s2i679349191\\upload" to tar ...
I0715 19:58:23.353582 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\HEAD as src/.git/HEAD
I0715 19:58:23.362580 03124 docker.go:478] Image contains io.openshift.s2i.scripts-url set to 'image:///usr/libexec/s2i'
I0715 19:58:23.365595 03124 docker.go:532] Base directory for STI scripts is '/usr/libexec/s2i'. Untarring destination is '/opt/s2i/destination'.
I0715 19:58:23.370579 03124 docker.go:546] Setting "/bin/sh -c tar -C /opt/s2i/destination -xf - && /usr/libexec/s2i/assemble" command for container ...
I0715 19:58:23.381581 03124 docker.go:594] Creating container with options {Name:"" Config:&{Hostname: Domainname: User: Memory:0 MemorySwap:0 MemoryReservation:0 KernelMemory:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:true AttachStderr:false PortSpecs:[] ExposedPorts:map[] StopSignal: Tty:false OpenStdin:true StdinOnce:true Env:[] Cmd:[/bin/sh -c tar -C /opt/s2i/destination -xf - && /usr/libexec/s2i/assemble] DNS:[] Image:s2i-wildfly-keycloak:latest Volumes:map[] VolumeDriver: VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[]} HostConfig:&{Binds:[] CapAdd:[] CapDrop:[] GroupAdd:[] ContainerIDFile: LxcConf:[] Privileged:false PortBindings:map[] Links:[] PublishAllPorts:false DNS:[] DNSOptions:[] DNSSearch:[] ExtraHosts:[] VolumesFrom:[] NetworkMode: IpcMode: PidMode: UTSMode: RestartPolicy:{Name: MaximumRetryCount:0} Devices:[] LogConfig:{Type: Config:map[]} ReadonlyRootfs:false SecurityOpt:[] CgroupParent: Memory:0 MemorySwap:0 MemorySwappiness:0 OOMKillDisable:false CPUShares:0 CPUSet: CPUSetCPUs: CPUSetMEMs: CPUQuota:0 CPUPeriod:0 BlkioWeight:0 Ulimits:[] VolumeDriver: OomScoreAdj:0}} ...
I0715 19:58:24.361582 03124 docker.go:625] Attaching to container "e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34" ...
I0715 19:58:24.366581 03124 docker.go:634] Starting container "e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34" ...
I0715 19:58:24.390581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\config as src/.git/config
I0715 19:58:24.394581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\description as src/.git/description
I0715 19:58:24.401579 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\applypatch-msg.sample as src/.git/hooks/applypatch-msg.sample
I0715 19:58:24.409581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\commit-msg.sample as src/.git/hooks/commit-msg.sample
I0715 19:58:24.416582 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\post-update.sample as src/.git/hooks/post-update.sample
I0715 19:58:24.423582 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\pre-applypatch.sample as src/.git/hooks/pre-applypatch.sample
I0715 19:58:24.430581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\pre-commit.sample as src/.git/hooks/pre-commit.sample
I0715 19:58:24.437581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\pre-push.sample as src/.git/hooks/pre-push.sample
I0715 19:58:24.443581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\pre-rebase.sample as src/.git/hooks/pre-rebase.sample
I0715 19:58:24.450581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\prepare-commit-msg.sample as src/.git/hooks/prepare-commit-msg.sample
I0715 19:58:24.457581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\hooks\update.sample as src/.git/hooks/update.sample
I0715 19:58:24.464582 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\index as src/.git/index
I0715 19:58:24.471580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\info\exclude as src/.git/info/exclude
I0715 19:58:24.477580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\logs\HEAD as src/.git/logs/HEAD
I0715 19:58:24.483580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\logs\refs\heads\master as src/.git/logs/refs/heads/master
I0715 19:58:24.489580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\logs\refs\remotes\origin\HEAD as src/.git/logs/refs/remotes/origin/HEAD
I0715 19:58:24.496595 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\objects\pack\pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.idx as src/.git/objects/pack/pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.idx
I0715 19:58:24.504580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\objects\pack\pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.pack as src/.git/objects/pack/pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.pack
I0715 19:58:24.512580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\packed-refs as src/.git/packed-refs
I0715 19:58:24.520581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\refs\heads\master as src/.git/refs/heads/master
I0715 19:58:24.530580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\refs\remotes\origin\HEAD as src/.git/refs/remotes/origin/HEAD
I0715 19:58:24.536579 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\README.md as src/README.md
I0715 19:58:24.541579 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\pom.xml as src/pom.xml
I0715 19:58:24.547581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\java\.gitkeep as src/src/main/java/.gitkeep
I0715 19:58:24.554579 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\java\Test.java as src/src/main/java/Test.java
I0715 19:58:24.560581 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\resources\.gitkeep as src/src/main/resources/.gitkeep
I0715 19:58:24.567580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\webapp\images\jbosscorp_logo.png as src/src/main/webapp/images/jbosscorp_logo.png
I0715 19:58:24.573582 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\webapp\index.html as src/src/main/webapp/index.html
I0715 19:58:24.580580 03124 tar.go:260] Adding to tar: C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\src\main\webapp\snoop.jsp as src/src/main/webapp/snoop.jsp
I0715 19:58:25.736835 03124 docker.go:658] Waiting for container "e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34" to stop ...
E0715 19:58:25.823198 03124 util.go:91] tar: src/.git/HEAD: time stamp 2016-07-15 22:58:23 is 47170.373018 s in the future
E0715 19:58:25.826197 03124 util.go:91] tar: src/.git/config: time stamp 2016-07-15 22:58:23 is 47170.3570716 s in the future
E0715 19:58:25.830196 03124 util.go:91] tar: src/.git/description: time stamp 2016-07-15 22:58:22 is 47169.3570195 s in the future
E0715 19:58:25.835195 03124 util.go:91] tar: src/.git/hooks/applypatch-msg.sample: time stamp 2016-07-15 22:58:22 is 47169.3569313 s in the future
E0715 19:58:25.839214 03124 util.go:91] tar: src/.git/hooks/commit-msg.sample: time stamp 2016-07-15 22:58:22 is 47169.3568811 s in the future
E0715 19:58:25.845198 03124 util.go:91] tar: src/.git/hooks/post-update.sample: time stamp 2016-07-15 22:58:22 is 47169.3568315 s in the future
E0715 19:58:25.850192 03124 util.go:91] tar: src/.git/hooks/pre-applypatch.sample: time stamp 2016-07-15 22:58:22 is 47169.3567858 s in the future
E0715 19:58:25.855194 03124 util.go:91] tar: src/.git/hooks/pre-commit.sample: time stamp 2016-07-15 22:58:22 is 47169.3567396 s in the future
E0715 19:58:25.860194 03124 util.go:91] tar: src/.git/hooks/pre-push.sample: time stamp 2016-07-15 22:58:22 is 47169.3566756 s in the future
E0715 19:58:25.865193 03124 util.go:91] tar: src/.git/hooks/pre-rebase.sample: time stamp 2016-07-15 22:58:22 is 47169.3566255 s in the future
E0715 19:58:25.870194 03124 util.go:91] tar: src/.git/hooks/prepare-commit-msg.sample: time stamp 2016-07-15 22:58:22 is 47169.3565782 s in the future
E0715 19:58:25.876196 03124 util.go:91] tar: src/.git/hooks/update.sample: time stamp 2016-07-15 22:58:22 is 47169.3565207 s in the future
E0715 19:58:25.880195 03124 util.go:91] tar: src/.git/index: time stamp 2016-07-15 22:58:23 is 47170.3564709 s in the future
E0715 19:58:25.885195 03124 util.go:91] tar: src/.git/info/exclude: time stamp 2016-07-15 22:58:22 is 47169.3563941 s in the future
E0715 19:58:25.893194 03124 util.go:91] tar: src/.git/logs/HEAD: time stamp 2016-07-15 22:58:23 is 47170.3563165 s in the future
E0715 19:58:25.896195 03124 util.go:91] tar: src/.git/logs/refs/heads/master: time stamp 2016-07-15 22:58:23 is 47170.3562097 s in the future
E0715 19:58:25.902195 03124 util.go:91] tar: src/.git/logs/refs/remotes/origin/HEAD: time stamp 2016-07-15 22:58:23 is 47170.3560995 s in the future
E0715 19:58:25.908194 03124 util.go:91] tar: src/.git/objects/pack/pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.idx: time stamp 2016-07-15 22:58:22 is 47169.355978 s in the future
E0715 19:58:25.914194 03124 util.go:91] tar: src/.git/objects/pack/pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.pack: time stamp 2016-07-15 22:58:22 is 47169.3553229 s in the future
E0715 19:58:25.922193 03124 util.go:91] tar: src/.git/packed-refs: time stamp 2016-07-15 22:58:22 is 47169.3550741 s in the future
E0715 19:58:25.925191 03124 util.go:91] tar: src/.git/refs/heads/master: time stamp 2016-07-15 22:58:23 is 47170.3547454 s in the future
E0715 19:58:25.932194 03124 util.go:91] tar: src/.git/refs/remotes/origin/HEAD: time stamp 2016-07-15 22:58:22 is 47169.3544162 s in the future
E0715 19:58:25.936192 03124 util.go:91] tar: src/README.md: time stamp 2016-07-15 22:58:23 is 47170.3541658 s in the future
E0715 19:58:25.941194 03124 util.go:91] tar: src/pom.xml: time stamp 2016-07-15 22:58:23 is 47170.353894 s in the future
E0715 19:58:25.945192 03124 util.go:91] tar: src/src/main/java/.gitkeep: time stamp 2016-07-15 22:58:23 is 47170.3536053 s in the future
E0715 19:58:25.951192 03124 util.go:91] tar: src/src/main/java/Test.java: time stamp 2016-07-15 22:58:23 is 47170.3533208 s in the future
E0715 19:58:25.957194 03124 util.go:91] tar: src/src/main/resources/.gitkeep: time stamp 2016-07-15 22:58:23 is 47170.3530891 s in the future
E0715 19:58:25.962191 03124 util.go:91] tar: src/src/main/webapp/images/jbosscorp_logo.png: time stamp 2016-07-15 22:58:23 is 47170.3528202 s in the future
E0715 19:58:25.968191 03124 util.go:91] tar: src/src/main/webapp/index.html: time stamp 2016-07-15 22:58:23 is 47170.3523545 s in the future
E0715 19:58:25.972193 03124 util.go:91] tar: src/src/main/webapp/snoop.jsp: time stamp 2016-07-15 22:58:23 is 47170.3521499 s in the future
I0715 19:58:26.002793 03124 sti.go:581] Found pom.xml... attempting to build with 'mvn package -Popenshift -DskipTests -B -s /opt/app-root/src/.m2/settings.xml'
I0715 19:58:27.569451 03124 sti.go:581] Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
I0715 19:58:27.572445 03124 sti.go:581] Maven home: /usr/local/apache-maven-3.3.9
I0715 19:58:27.575447 03124 sti.go:581] Java version: 1.8.0_91, vendor: Oracle Corporation
I0715 19:58:27.581444 03124 sti.go:581] Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el7_2.x86_64/jre
I0715 19:58:27.585451 03124 sti.go:581] Default locale: en_US, platform encoding: ANSI_X3.4-1968
I0715 19:58:27.590450 03124 sti.go:581] OS name: "linux", version: "4.4.15-moby", arch: "amd64", family: "unix"
I0715 19:58:29.911133 03124 sti.go:581] [INFO] Scanning for projects...
I0715 19:58:30.078958 03124 sti.go:581] [INFO]
I0715 19:58:30.079959 03124 sti.go:581] [INFO] ------------------------------------------------------------------------
I0715 19:58:30.082958 03124 sti.go:581] [INFO] Building SampleApp 1.0
I0715 19:58:30.086962 03124 sti.go:581] [INFO] ------------------------------------------------------------------------
I0715 19:58:30.596006 03124 sti.go:581] [INFO] Downloading:......

............................................... 

I0715 20:00:28.337425 03124 docker.go:687] Invoking postExecution function
I0715 20:01:03.670876 03124 sti.go:288] No user environment provided (no environment file found in application sources)
I0715 20:01:03.711877 03124 docker.go:734] Committing container with dockerOpts: {Container:e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34 Repository:openshift-test Tag: Message: Author: Run:0xc0820fa380}, config: {Hostname: Domainname: User:1001 Memory:0 MemorySwap:0 MemoryReservation:0 KernelMemory:0 CPUShares:0 CPUSet: AttachStdin:false AttachStdout:false AttachStderr:false PortSpecs:[] ExposedPorts:map[] StopSignal: Tty:false OpenStdin:false StdinOnce:false Env:[] Cmd:[/usr/libexec/s2i/run] DNS:[] Image: Volumes:map[] VolumeDriver: VolumesFrom: WorkingDir: MacAddress: Entrypoint:[] NetworkDisabled:false SecurityOpts:[] OnBuild:[] Mounts:[] Labels:map[io.openshift.tags:builder,wildfly,wildfly10,keycloak
build-date:20160701 io.openshift.s2i.scripts-url:image:///usr/libexec/s2i vendor:CentOS io.openshift.s2i.build.commit.author:Ariel Carrera <carreraariel@gmail.com> io.k8s.description:Aplicaciones JEE en Wildfly 10.0.0.Final y Keycloak 1.9.8.Final io.s2i.scripts-url:image:///usr/libexec/s2i io.k8s.display-name:openshift-test io.openshift.s2i.build.source-location:file://C:\Desarrollo\workspace_sy\openshift\test\s2i-wildfly-keycloak\test\test-app\ io.openshift.s2i.build.commit.ref:master io.openshift.expose-services:8080:http,8787:http,9090:http license:GPLv2 io.openshift.builder-base-version:e178f1c io.openshift.s2i.build.commit.message:Test io.openshift.s2i.build.commit.id:a7c604210764b71ad217e488dc62a8a52fa5bfef io.openshift.builder-version:71d72b4 io.openshift.s2i.destination:/opt/s2i/destination name:CentOS Base Image io.openshift.s2i.build.image:s2i-wildfly-keycloak io.openshift.s2i.build.commit.date:Fri Jul 15 12:49:44 2016 -0300]}
I0715 20:01:04.967792 03124 sti.go:333] Successfully built openshift-test
I0715 20:01:04.971787 03124 docker.go:608] Removing container "e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34" ...
I0715 20:01:05.195145 03124 docker.go:612] Removed container "e9de77bb1bcdbd4aa4e239b75345497b02a7f3ac095e444f7fe1a51afd846c34"
I0715 20:01:05.198147 03124 cleanup.go:31] Removing temporary directory C:\Users\Ariel\AppData\Local\Temp\s2i679349191
I0715 20:01:05.202148 03124 fs.go:156] Removing directory 'C:\Users\Ariel\AppData\Local\Temp\s2i679349191'
E0715 20:01:05.224143 03124 fs.go:160] Error removing directory 'C:\Users\Ariel\AppData\Local\Temp\s2i679349191': remove C:\Users\Ariel\AppData\Local\Temp\s2i679349191\upload\src\.git\objects\pack\pack-6b709abdd06eddcc0a70a2166de7e20a4b473d93.idx: Acceso denegado.

**Comment by bparees** [comment] 2016-07-18 01:16
@csrwng do you have a windows (windows 10 it seems) machine available to try to recreate this?

@arielcarrera do you know if this issue happens on other versions of windows?

**Comment by arielcarrera** [comment] 2016-07-18 21:24
Hi Ben, I don't know, I have tried only with Windows 10. Furthermore, The new "Docker for Windows" is only available for Windows 10.

**Comment by csrwng** [comment] 2016-07-18 21:59
Yup, I can reproduce locally as well. It's caused by this issue: https://github.com/golang/go/issues/9606
It looks like a fix will be included in go 1.7

In the meantime, we have 2 options:
1. Log the error as a warning since it doesn't affect the creation of a new image, it's only cleanup
2. Recursively remove read-only attribute from directories before we delete them on windows

@bparees preference?

**Comment by bparees** [comment] 2016-07-18 22:02
thanks @csrwng.  i prefer the second option, so we actually clean up.

**Comment by csrwng** [comment] 2016-08-02 17:37
Fixed with https://github.com/openshift/source-to-image/pull/547

**Closed by csrwng** 2016-08-02 17:37 UTC
Labels: kind/bug, priority/P2
