### ISSUE TITLE
s2i build on OSX => fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by harobed** [openshift/source-to-image#639] opened 2016-11-17 14:30 UTC
I have this error:

https://gist.github.com/harobed/a3acf12956d073f1f8378379aea46764

Information about my host:

```
$ s2i version
s2i v1.1.3
```

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

```
$ docker info
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 71
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: EINF:6OM6:4537:3WUL:3GJE:W42O:HJGQ:U22H:4VBP:PXMP:EQGO:43OL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-11-17T14:06:42.466914005Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by harobed** [comment] 2016-11-17 15:29
My repository source size is 120 Mo

**Comment by harobed** [comment] 2016-11-17 16:00
I've rebuild `dae276c287c069e3ed96b2cb085cb3f61decfea6` version on my host and `s2i build` work perfectly. I'll try with `ddb10f16412977688136b77c76c30c0632e510d6`.

**Comment by harobed** [comment] 2016-11-17 16:11
> I'll try with ddb10f16412977688136b77c76c30c0632e510d6

no problem with this version.

To build I use:

```
./hack/build-go.sh
```

I've try:

```
./hack/build-release.sh
++ Building openshift/sti-release
^C
```

But it wait endlessly.

**Comment by bparees** [comment] 2017-02-06 13:58
@csrwng can you take a look at this mac issue?  (hopefully resolved in later versions, give its age)

**Comment by csrwng** [comment] 2017-02-06 15:41
@harobed are you using golang 1.7? earlier versions of golang are not compatible with MacOS Sierra. I have no problem compiling the latest master locally (on MacOS Sierra 10.12.3, go v1.7.5).

I will close this, since I can't reproduce. If you still have a problem please reopen.

**Closed by csrwng** 2017-02-06 15:41 UTC
Labels: kind/bug, priority/P2
