### ISSUE TITLE
Auth via credsStore is not supported

### ISSUE THREAD

**Issue by Fodoj** [openshift/source-to-image#698] opened 2017-03-08 14:37 UTC
In some environments, specifically in AWS and GCE, credentials are provided via credentials store, as documented here: https://docs.docker.com/engine/reference/commandline/login/#credentials-store. 

s2i doesn't seem to be able to handle this configuration:

```
$ cat ~/.docker/config.json
{
  "credsStore": "ecr-login"
}
```

```
$ s2i build https://github.com/openshift/ruby-hello-world centos/ruby-23-centos7 test-ruby-app 

error: Unable to load docker config: json: cannot unmarshal string into Go value of type docker.dockerConfig
```

**Comment by gabemontero** [comment] 2017-03-08 15:26
`s2` is using the docker engine-api under the covers, and if you look at  https://github.com/docker/engine-api/blob/master/types/auth.go it does not include credStore, so the json unmarshalling for `s2i` ultimately is not currently mapping that type of config.

I believe there has been talk of engine-api being deprecated and needing to move to docker/docker but I don't know the specifics off hand as to schedules and roadmaps.

@openshift/devex - does anybody know more of the specifics here?

**Comment by coreydaley** [comment] 2017-03-08 15:28
There is currently an issue open for deprecating docker-engine on this repo: https://github.com/openshift/source-to-image/issues/659

**Comment by bparees** [comment] 2017-03-09 03:45
closing this as a dupe of https://github.com/openshift/source-to-image/issues/659, thanks @gabemontero and @coreydaley

**Closed by bparees** 2017-03-09 03:45 UTC
