### ISSUE TITLE
Ignoring files

### ISSUE THREAD

**Issue by Maxim-Filimonov** [openshift/source-to-image#197] opened 2015-05-22 14:30 UTC
During investigation of a very big image sizes produced by STI I have found that STI ignores completely .gitignore or .dockerignore and puts every folder into the container it is building. 
We have some temporarily files which are ignored in both git and dockerignore with significant weight(about 125MB) adding quite a lot of unnecessary data to production image. I cannot find a way to make STI ignore those files. Would be good if STI can read .dockerignore or .gitignore to get this files and do not put them inside the container.

**Comment by bparees** [comment] 2015-05-22 14:37
STI does a git clone of your repo, so if you have files that are in your .gitignore, why are they in your repo in the first place?

**Comment by soltysh** [comment] 2015-05-22 22:25
Is this a continuation of the problem you described in #196 or something different?

**Comment by Maxim-Filimonov** [comment] 2015-05-22 23:16
@bparees we don't use git clone. As we are running sti on CI we just use 'sti build .' inside checked out folder. Files there are artifacts from running tests inside the same folder and mongodb journal from tests again. With docker directly we just added those files to .dockerignore while I can't wait the wait to do it with sti.
@soltysh it is different problem

**Comment by bparees** [comment] 2015-05-22 23:24
Though it's it's not an ideal solution, for now you could make a custom assemble script that deletes the files you don't care about as part of the "build". 

Ben Parees | OpenShift

**Comment by Maxim-Filimonov** [comment] 2015-05-22 23:31
@bparees yeah i'm gonna do exactly that for `tmp/cache` as it's not needed for running app. But it still takes 2 minutes to transfer all those files inside the image before the build. I'll try to hack some PR over weekend

**Comment by bparees** [comment] 2015-05-23 01:31
Cool, just a thought as you're working on it....we'd probably prefer to introduce a new ".stiignore" file over using existing files so we don't get unintended behavior.  

If you do want to use add a patch to respect existing .dockerignore/.gitignore files i think it would be best to do it as a non-default flag that must be passed to STI, again to avoid unexpected behavior for users in which files don't get included.

**Comment by soltysh** [comment] 2015-05-25 09:46
@bparees since under the covers we do actually docker build, I don't mind us reusing .dockerignore. Especially if somebody already has one. One other options would be to treat those files (.stiignore and .dockerignore) equally, meaning the same format and behavior.

**Comment by bparees** [comment] 2015-05-25 14:06
We don't always do a docker build under the covers. Only under certain circumstances right? 

Ben Parees | OpenShift

**Comment by soltysh** [comment] 2015-05-25 14:08
Right, that was a shortcut in my head :wink:

**Comment by Maxim-Filimonov** [comment] 2015-05-26 01:45
@bparees Yeah I hacked something locally but trying to figure out how to make it build the local version from inside docker machine is not trivial :\ Hacking.md doesn't seem to help as I cannot push the version to github.
I was thinking to either make an option which allows to add exclude patterns something like
```
sti --exclude 'public/uploads'
```
Or or just do
```
sti --exclude-from '.dockerignore'
```
That way existing behaviour doesn't change in case if someone relies on it.

**Comment by soltysh** [comment] 2015-05-26 07:41
@Maxim-Filimonov what's your exact problem with building sti? I see that our Hacking.md only tells about building a release and testing, but it's missing local development description. I'll fix that later today. For now all you need to know is we provide you with a `Makefile` which has following targets:
- `build` - builds STI;
- `clean` - clean build artifacts;
- `test` - runs `hack/test-go.sh`;
Additionally we run integration tests with `hack/test-integration.sh`. Upon build the `sti` binary will be available in `_output/local/go/bin/` directory.

As for the flag, I'd suggest the first two options, where you can either specify exclude *pattern* (`--exclude 'public/*'`)  and exclude file (`--exclude-from '.dockeringore'`), similarly to what [grep](http://www.gnu.org/software/grep/manual/grep.html#File-and-Directory-Selection) offers, for example. With the two, we'll have enough flexibility for exclusions.

**Comment by gabemontero** [comment] 2015-07-23 02:50
I have a prototype of a .s2iignore file working.  However, as part of moving this to the next step, I'm at a point where a decision on whether to support .gitignore or .dockerignore capabilities (I would call .dockerignore a subset of .gitignore since it is not recursive), or maybe even a subset of .dockerignore (if we want something simpler).

.dockerignore does interface with Go a bit more directly (Globbing is done with filepath.Match), if that helps influence the decision.

Some links for reference:
http://git-scm.com/docs/gitignore
https://docs.docker.com/reference/builder/#dockerignore-file

**Comment by Maxim-Filimonov** [comment] 2015-07-23 12:44
For my purposes .dockerignore as a first step will be sufficient enough to close the issue.

**Closed** 2015-07-29 19:00 UTC
Labels: kind/enhancement, priority/P3
