### ISSUE TITLE
Source files are extracted in the wrong location.

### ISSUE THREAD

**Issue by afilimonov** [openshift/source-to-image#419] opened 2016-03-01 02:30 UTC
s2i v 1.0.5
Performing a clean build results in some source files in the wrong location. E.g. (untar location is /var/aem) log files shows:

I0229 19:49:34.461870 66911 tar.go:260] Adding to tar: /var/folders/sz/033nkcsn2xn06d798rygg7nd7w0cfp/T/s2i908932906/upload/src/bundle/src/main/java/com/aem/kickstarter/ui/bean/component/page/AEMKickstarterMasterPageBean.java as src/bundle/src/main/java/com/aem/kickstarter/ui/bean/component/page/AEMKickstarterMasterPageBean.java

In the container AEMKickstarterMasterPageBean.java file is placed in:
/var/aem/AEMKickstarterMasterPageBean.java

Approximately 50% of source files are misplaced. I'm attaching s2i log file and also log showing contents of untar destination folder /var/aem with all misplaced files.
[logs.zip](https://github.com/openshift/source-to-image/files/152067/logs.zip)

**Comment by afilimonov** [comment] 2016-03-01 21:07
Yes the destination location was intentionally set incorrectly to stop the build which runs several minutes. The problem is that some files are extracted incorrectly. E.g. for src/bundle/src/main/java/com/aem/kickstarter/ui/bean/component/page/AEMKickstarterMasterPageBean.java the directory structure is lost and the file is placed in the root.

Update: it seems like this issue for OSX. The build works fine in OSE 3.1. Perhaps OSX tar (bsdtar) is not compatible with CentOS GNU tar?

**Comment by bparees** [comment] 2016-03-01 21:23
@csrwng can you take a peek at this since you have a mac?

**Comment by afilimonov** [comment] 2016-03-02 17:04
I created a [test](https://github.com/afilimonov/s2i-test) that consistently reproduces this problem for me in OSX/Docker/VirtualBox environment

**Comment by php-coder** [comment] 2016-05-20 10:18
I could try to fix it but only if you provide the steps for reproducing it. As far I understand, I need to install s2i binary, I already have VirtualBox installed, so I need to make docker available on the host system, right? How I can do that, BTW? Do you use docker-machine or something like that?

**Comment by afilimonov** [comment] 2016-05-20 13:44
Yes docker-machine 0.6.0

**Comment by csrwng** [comment] 2016-08-01 18:28
@afilimonov are you still able to reproduce this issue? I tried recently with both Docker beta for Mac and docker-machine on Mac and could not reproduce. (v1.12)

**Comment by csrwng** [comment] 2016-09-30 03:53
Closing this due to age, but please reopen if issue persists. I cannot reproduce locally.

**Closed by csrwng** 2016-09-30 03:53 UTC
Labels: priority/P2

**Comment by renatoppuccini** [comment] 2017-08-03 13:48
I got a similar issue when s2i from a githut repo, but using a branch and contextDir using OpenShift 3.3

I0802 21:17:02.776536       1 glog.go:50] Setting build revision to &api.GitSourceRevision{Commit:"28fe372a015c502cc626ca806a8bc09b5c346e61", Author:api.SourceControlUser{Name:"Pete Muir", Email:"pmuir@bleepbleep.org.uk"}, Committer:api.SourceControlUser{Name:"Pete Muir", Email:"pmuir@bleepbleep.org.uk"}, Message:"Prepare for release of 7.0.0.Final"}
I0802 21:17:02.916596       1 cleanup.go:33] Removing temporary directory /tmp/s2i-build489606146
I0802 21:17:03.004292       1 fs.go:159] Removing directory '/tmp/s2i-build489606146'
F0802 21:17:03.046902 1 helpers.go:110] error: build error: rename /tmp/s2i-build489606146/tmp/helloworld /tmp/s2i-build489606146/upload/src: no such file or directory

--

**Comment by coreydaley** [comment] 2017-08-04 13:20
@renatoppuccini Can you please supply the full command that you used to create the application?

**Comment by Computician** [comment] 2017-10-11 20:24
FWIW, I am having the same issue. Numerous files are extracted from the archive into `/tmp` instead of their originally archived directory `/tmp/stc/original/path/to/file`.

This is on OSX 10.11.6, s2i v1.1.7 and v1.1.6 being extracted onto a Centos7 image.

This is a Java application with some nasty directories, but none of them are above 256 bytes in length from what I can tell (double checking).

**Comment by csrwng** [comment] 2017-10-12 11:10
@Computician is this a public repository that we can use to reproduce locally?

**Comment by Computician** [comment] 2017-10-12 12:32
@csrwng sadly no. Let me see if I can create a test application that causes the same failure.

**Comment by Computician** [comment] 2018-03-23 18:16
@csrwng Well, I abandoned this thread...However, https://github.com/computician/javaplay recreates the issue. When gradle tries to build inside the s2i process I get the error
```
opt/app-root/src/src/main/java/io/github/computician/enterprise/resources/Helloworld.java:3: error: package io.github.computician.enterprise.entities.subdir.subsubdir does not exist
import io.github.computician.enterprise.entities.subdir.subsubdir.HelloworldObjectFactoryGeneratorReallyLongEnterprisyName;
                                                                 ^
```
And the build fails. This is on the latest s2i release on El Capitan.
