### ISSUE TITLE
s2i v1.1.2 reports malformed HTTP response (Docker Toolbox in Windows 10)

### ISSUE THREAD

**Issue by rjstone** [openshift/source-to-image#603] opened 2016-10-05 07:12 UTC
On Windows 10 running Docker Toolbox. (uses virtualbox, no Hyper-V available)

```
I1005 02:21:55.886941    8336 docker.go:517] error inspecting image centos/python-35-centos7:latest: Get http://192.168.99.100:2376/images/centos/python-35-centos7:latest/json?size=1: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
```

It's correctly picking up the docker vm from the env as --url="tcp://192.168.99.100:2376"

docker command works just fine and uses this ip:port

**Versions:**  s2i v1.1.2 docker client: 1.12.0 docker server: 1.12.1 API version: 1.24

**Everything works fine if I use s2i v1.1.1** so it seems to be a problem with windows s2i v1.1.2

**Comment by bparees** [comment] 2016-10-05 15:28
looks like something is attempting an http request against an https endpoint.

**Comment by rjstone** [comment] 2016-10-05 16:24
I tried variations on the url tcp://192.168.99.100:2376 such as https://192.168.99.100:2376 but it didn't make any difference.

--loglevel=5 revealed it was reading the credential files. Here's the full output:

```
$ s2i-v1-1-2.exe build git://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app --loglevel=5
I1005 12:23:14.699692   19096 main.go:68] Running S2I version "v1.1.2"
I1005 12:23:14.704695   19096 util.go:57] Getting docker credentials for centos/ruby-22-centos7
I1005 12:23:14.704695   19096 util.go:69] Using  credentials for pulling centos/ruby-22-centos7
I1005 12:23:14.716203   19096 docker.go:306] Connecting to docker on tcp://192.168.99.100:2376
I1005 12:23:14.722708   19096 docker.go:559] error inspecting image centos/ruby-22-centos7:latest: Get http://192.168.99.100:2376/images/centos/ruby-22-centos7:latest/json?size=1: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
I1005 12:23:14.748226   19096 docker.go:517] error inspecting image centos/ruby-22-centos7:latest: Get http://192.168.99.100:2376/images/centos/ruby-22-centos7:latest/json?size=1: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
I1005 12:23:14.749227   19096 main.go:147]
Error describing image:         unable to get metadata for centos/ruby-22-centos7:latest
Source:                         git://github.com/openshift/ruby-hello-world
Output Image Tag:               hello-world-app
Environment:
Incremental Build:              disabled
Remove Old Build:               disabled
Builder Pull Policy:            if-not-present
Previous Image Pull Policy:     if-not-present
Quiet:                          disabled
Layered Build:                  disabled
Docker Endpoint:                tcp://192.168.99.100:2376
Docker Pull Config:             C:\Users\Robert\.docker\config.json
Docker Pull User:               rjstone

I1005 12:23:14.751728   19096 docker.go:306] Connecting to docker on tcp://192.168.99.100:2376
F1005 12:23:14.751728   19096 main.go:150] Unable to connect to Docker daemon. Please set the DOCKER_HOST or make sure the Docker socket "tcp://192.168.99.100:2376" exists
```

**Comment by jim-minter** [comment] 2016-10-05 16:45
Hi @rjstone AFAICS s2i is expecting the DOCKER_CERT_PATH environment variable to point towards a local directory holding files ca.pem, cert.pem and key.pem.  I think these should be laid down somewhere for you by Docker Toolbox.  If this is done, s2i should then connect using TLS.

(We changed s2i to use the official docker API client between v1.1.1 and v1.1.2, which is why this behaviour has changed).

Please can you check that DOCKER_CERT_PATH is set up sanely?  http://stackoverflow.com/questions/32047660/docker-for-windows-not-working may be of use.

Please let me know either way and I'll investigate further as necessary.

**Comment by rjstone** [comment] 2016-10-05 18:22
@jim-minter That's all set. This is the same shell environment where I've been using docker, docker-machine, etc, for quite a while with no problem. Output:

```
Robert@crimson  ~/Documents/GitHub/source-to-image (master)
$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_MACHINE_NAME=default
DOCKER_TLS_VERIFY=1
DOCKER_TOOLBOX_INSTALL_PATH=C:\Program Files\Docker Toolbox
DOCKER_CERT_PATH=C:\Users\Robert\.docker\machine\machines\default
```
v1.1.2:
```
$ s2i-v1-1-2.exe
Source-to-image (S2I) is a tool for building repeatable docker images.

A command line interface that injects and assembles source code into a docker image.
Complete documentation is available at http://github.com/openshift/source-to-image

Usage:
  s2i [flags]
  s2i [command]

Available Commands:
  version           Display version
  build             Build a new image
  rebuild           Rebuild an existing image
  usage             Print usage of the assemble script associated with the image
  create            Bootstrap a new S2I image repository
  genbashcompletion Generate Bash completion for the s2i command

Flags:
      --ca="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\ca.pem": Set the path of the docker TLS ca file
      --cert="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\cert.pem": Set the path of the docker TLS certificate file
  -h, --help[=false]: help for s2i
      --key="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\key.pem": Set the path of the docker TLS key file
      --log-flush-frequency=5s: Maximum number of seconds between log flushes
      --loglevel=0: Set the level of log output (0-5)
  -U, --url="tcp://192.168.99.100:2376": Set the url of the docker socket to use

Use "s2i [command] --help" for more information about a command.
```
v1.1.1:
```
Robert@crimson  ~/Documents/GitHub/source-to-image (master)
$ s2i
Source-to-image (S2I) is a tool for building repeatable docker images.

A command line interface that injects and assembles source code into a docker image.
Complete documentation is available at http://github.com/openshift/source-to-image

Usage:
  s2i [flags]
  s2i [command]

Available Commands:
  version           Display version
  build             Build a new image
  rebuild           Rebuild an existing image
  usage             Print usage of the assemble script associated with the image
  create            Bootstrap a new S2I image repository
  genbashcompletion Generate Bash completion for the s2i command

Flags:
      --ca="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\ca.pem": Set the path of the docker TLS ca file
      --cert="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\cert.pem": Set the path of the docker TLS certificate file
  -h, --help[=false]: help for s2i
      --key="C:\\Users\\Robert\\.docker\\machine\\machines\\default\\key.pem": Set the path of the docker TLS key file
      --loglevel=0: Set the level of log output (0-5)
  -U, --url="tcp://192.168.99.100:2376": Set the url of the docker socket to use

Use "s2i [command] --help" for more information about a command.
```
Files:
```
Robert@crimson  ~/Documents/GitHub/source-to-image (master)
$ cd /c/Users/Robert/.docker/machine/machines/default/

Robert@crimson  ~/.docker/machine/machines/default
$ ls -l
total 3085729
-rw-r--r-- 1 Robert 197121   39845888 Oct  1 02:42 boot2docker.iso
-rw-r--r-- 1 Robert 197121       1034 Oct  4 04:54 ca.pem
-rw-r--r-- 1 Robert 197121       1078 Oct  4 04:54 cert.pem
-rw-r--r-- 1 Robert 197121       2977 Oct  5 07:54 config.json
drwxr-xr-x 1 Robert 197121          0 Oct  4 04:53 default/
-rw-r--r-- 1 Robert 197121 3119579136 Oct  5 08:04 disk.vmdk
-rw-r--r-- 1 Robert 197121       1675 Sep 12 23:44 id_rsa
-rw-r--r-- 1 Robert 197121        381 Sep 12 23:44 id_rsa.pub
-rw-r--r-- 1 Robert 197121       1679 Oct  4 04:54 key.pem
-rw-r--r-- 1 Robert 197121       1107 Oct  4 04:54 server.pem
-rw-r--r-- 1 Robert 197121       1675 Oct  4 04:54 server-key.pem
```

**Comment by gabemontero** [comment] 2016-10-05 18:26
Yep s2i within origin needs the env var (and k8s ensures they are set), but
s2i the standalone program can also leverage the args noted.

**Comment by jim-minter** [comment] 2016-10-05 21:24
@rjstone You're completely right. I believe I can also reproduce what you've reported on Fedora (with a pile of certs and an ncat server for now).

```
DOCKER_TLS_VERIFY=1 DOCKER_HOST=docker://localhost:1234 DOCKER_CERT_PATH=/tmp/certs s2i build git://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app
```

Evidently v1.1.2 (5732fdd) is broken.  However in fact the very next merge commit c107c6b5f9528e15076ade75fa384788aea178a9 and HEAD look more healthy (at least, I can see they're sending a TLS handshake rather than raw HTTP).

@bparees @gabemontero I'm going to need a bit of assistance with this.  Ben's "cleanup godeps" commit is a big one and at this stage I'm not sure what its goal is or what part of it is responsible for changing this functionality for the better.  Also I'm concerned that we're trying to use command line arguments and environment variables to represent the same config and it doesn't feel like a good plan at first glance.  After understanding this fully I'm guessing some additional test cases would be appropriate and I'm guessing we'll need to create a new release as well.

**Comment by rjstone** [comment] 2016-10-05 22:55
I was going to try to see if HEAD worked but ran into build problems. What is the recommended build environment for this in Windows? When I try to use mingw32-make the `ln` utility it comes with dies on a long pathname. (Sad but after all these years things in Windows are still breaking due to "640K ought to be enough for anyone" type stuff.)

**Comment by bparees** [comment] 2016-10-06 01:52
@jim-minter you can ignore all the godep changes I think, the relevant commit is this one from that PR: https://github.com/openshift/source-to-image/pull/596/commits/7032fa4c49737d366f8640f96104639fd9ef0385

i'm not really sure why that would matter either, but certainly changing how we inspect images could have impacted this flow, since the old code (that used the kube apis) was doing a lot more.

**Comment by bparees** [comment] 2016-10-06 01:54
@rjstone we build the windows release from linux using cross compiling(hack/build-release.sh), not sure the last time someone attempted to do a build directly on windows.

**Comment by jim-minter** [comment] 2016-10-06 07:10
OK, I don't think HEAD actually works either.  The issue is in the way that we initialise the k8s docker client.  #596 changes the error behaviour because it uses the docker engine client for the very first API call (which appears to work in this configuration), but subsequent calls then fail because they use the k8s client.

https://github.com/jim-minter/source-to-image/commit/4c250cca9752a956b4017b6339d834d029017660 is a hack which at least helps in this particular case, but it's by no means the complete fix required.  I'm in meetings today but should be able to take a look at this properly on Friday.

**Comment by jim-minter** [comment] 2016-10-06 07:11
And I think there's a further issue that needs to be looked at around support of DOCKER_HOST=tcp:// rather than DOCKER_HOST=https:// ...

**Comment by rjstone** [comment] 2016-10-06 17:16
FYI just in case it's useful:

There are two possible docker environments in windows. "Docker Toolbox" uses virtualbox to set up a VM running boot2docker and this is what anyone who doesn't have Hyper-V support (lacking Win10 pro/enterprise/server) has to use. It appears to be based on "Docker for Mac". This comes with a "Docker Quickstart Terminal" application that sets all the environment variables so that the docker commands work. ("Docker Quickstart Terminal" is a wrapper around "Git Bash" which is itself a wrapper around MinGW64 bash.) So "Docker Quickstart Terminal" seems like the most likely environment in which someone would try to run s2i if using Docker Toolbox, so it seems like a good test case. It uses the "tcp://" URL to point to the dockerd service on the VM.

The other is "Docker for Windows" which uses Hyper-V. (I'm not using this because I'm not using Win10 pro and thus don't have Hyper-V.) I'm pretty sure this runs windows service versions of dockerd and docker-containerd, and I'm also pretty sure that it uses a named pipe for the connection to the windows service instead of TCP/TLS. So this is yet another windows case where a different connection method is used. [Docs](https://docs.docker.com/docker-for-windows/faqs/#/how-do-i-connect-to-the-remote-docker-engine-api) say:

"On Docker for Windows, clients can connect to the Docker Engine through a named pipe: npipe:////./pipe/docker_engine, or TCP socket at this URL: http://localhost:2375."

**Comment by bparees** [comment] 2016-10-09 23:48
lumping all the reported issues in the space together:
https://github.com/openshift/source-to-image/issues/597
https://github.com/openshift/source-to-image/issues/604

guessing they all have a common/related root cause related to the changes to use the k8s apis for talking to docker, as @jim-minter has drilled into so far.

**Comment by jim-minter** [comment] 2016-10-20 20:45
Hi @rjstone a patch that should fix this is now merged, if you can test against HEAD I'd be interested to know if it resolves your issue.

**Closed** 2016-11-30 15:47 UTC
