### ISSUE TITLE
sti rebuild fails with index out of range

### ISSUE THREAD

**Issue by dhirajsb** [openshift/source-to-image#257] opened 2015-08-11 20:54 UTC
The sti and sample app are on github, running the following commands causes an index out of range

```shell
rh-wfh-dbokde:camel-hello-world dbokde$ sti build https://github.com/dhirajsb/camel-hello-world dhirajsb/karaf4-sti camel-hello-world-sti
rh-wfh-dbokde:camel-hello-world dbokde$ sti rebuild --force-pull=false camel-hello-world-sti --loglevel=5
I0811 13:42:20.466769 60224 util.go:34] Using dhirajsb@gmail.com credentials for pulling camel-hello-world-sti
I0811 13:42:20.479539 60224 docker.go:199] Image camel-hello-world-sti:latest available locally
panic: runtime error: index out of range

goroutine 1 [running]:
main.func·004(0x208760ea0, 0x20875d5c0, 0x1, 0x3)
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/sti/main.go:217 +0x694
github.com/spf13/cobra.(*Command).execute(0x208760ea0, 0x20875d500, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:476 +0x65c
github.com/spf13/cobra.(*Command).Execute(0x208760820, 0x0, 0x0)
	/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/spf13/cobra/command.go:541 +0x18d
main.main()
	/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/cmd/sti/main.go:366 +0x619

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x68b1e0)
	/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/golang/glog/glog.go:839 +0x78
created by github.com/golang/glog.init·1
	/go/src/github.com/openshift/source-to-image/Godeps/_workspace/src/github.com/golang/glog/glog.go:406 +0x2a7

goroutine 7 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/lib/golang/src/os/signal/signal_unix.go:27 +0x35

goroutine 9 [runnable]:
net/http.(*persistConn).readLoop(0x2087b4160)
	/usr/lib/golang/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:660 +0xc9f

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0x2087b4160)
	/usr/lib/golang/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:661 +0xcbc
rh-wfh-dbokde:camel-hello-world dbokde$
```

**Comment by mfojtik** [comment] 2015-08-17 09:54
@dhirajsb I can't reproduce this using the `sti` binary built from the master. Can you please try to update?

```console
π ~/sandbox sti rebuild --force-pull=false camel-hello-world-sti --loglevel=5
I0817 11:54:26.366665 20035 docker.go:211] Image camel-hello-world-sti:latest available locally
I0817 11:54:26.369945 20035 docker.go:211] Image dhirajsb/karaf4-sti:latest available locally

Application Name:	camel-hello-world-sti
Description:		Platform for building and running Karaf4 based applications
Builder Name:		Karaf4
Builder Image:		dhirajsb/karaf4-sti
Source:			https://github.com/dhirajsb/camel-hello-world
Source Ref:		master
Output Image Tag:	camel-hello-world-sti
Incremental Build:	enabled
Remove Old Build:	disabled
Force Pull:		disabled
Quiet:			disabled
Layered Build:		disabled
STI Scripts URL:	https://raw.githubusercontent.com/dhirajsb/karaf4-sti/master/.sti/bin/
Docker Endpoint:	unix:///var/run/docker.sock

I0817 11:54:26.373298 20035 docker.go:211] Image dhirajsb/karaf4-sti:latest available locally
I0817 11:54:26.377871 20035 sti.go:113] Preparing to build camel-hello-world-sti
I0817 11:54:26.378053 20035 clone.go:28] Cloning into /tmp/sti613751614/upload/src
```

**Comment by dhirajsb** [comment] 2015-08-19 04:38
Is it possible the issue was in v1.0.1 and has since been fixed on master? Maybe if you can quickly test it against 1.0.1 and it causes the same error then we'd know it's been fixed on master.

**Comment by bparees** [comment] 2015-10-02 14:56
@dhirajsb can you try this with the 1.0.2 release?

**Comment by bparees** [comment] 2015-10-06 06:42
closing as i believe it is fixed, @dhirajsb if you are able to reproduce with v1.0.2, please reopen.

**Closed by bparees** 2015-10-06 06:42 UTC
