### ISSUE TITLE
reported log lines are wrong

### ISSUE THREAD

**Issue by bparees** [openshift/source-to-image#558] opened 2016-08-05 03:32 UTC
run:
s2i build https://github.com/openshift/nodejs-ex centos/nodejs-4-centos7  --loglevel=5 

you will see in the output:
```
E0804 23:28:46.056805   28401 postexecutorstep.go:328] npm info it worked if it 
ends with ok
```

but the output is actually being logged by:
https://github.com/openshift/source-to-image/blob/master/pkg/build/strategies/sti/sti.go#L587

(the postexecutorstep isn't being invoked at all because this isn't an extended build).

bafflingly, if you comment out the postexecutor step line, you'll see the log attributed to yet another incorrect location.  If you then comment out *that* location, the reporting is correct.

Also if you change the postexecutor code to instead log to info instead of err, the reported location changes.

So something very weird is going on w/ the stack frame attribution, possibly due to the presence of go routines, but it makes no sense to me that it's getting attributed to code that's not even being invoked in these flows (i added print statements to confirm that).

**Comment by bparees** [comment] 2016-08-05 03:33
note that https://github.com/openshift/source-to-image/pull/557 will change this behavior slightly, but it will still not report the line number correctly.

**Comment by bparees** [comment] 2016-08-05 03:33
@php-coder fyi, though i don't think this relates to your extended build work. but just in case you have a thought.

**Comment by php-coder** [comment] 2016-08-05 09:02
@bparees If you remember, I was suggesting to add a prefixes to the messages that came from scripts. It won't fix wrong lines but at least helps to quickly understand that errors came not from S2I code but from the one of user-provided scripts.

**Comment by bparees** [comment] 2016-08-05 13:37
@php-coder yes but that's not my primary concern here, i'm worried about us trying to debug later and not understanding what code is actually executing (especially if this is not the only place where the misreporting is happening).

if we report the correct line numbers, it's easy to go to that line number and understand the output is coming from the container/script in the container.  if we report the wrong one, it can really send you down a bad debugging path.

**Comment by jupierce** [comment] 2016-08-11 14:13
@bparees This is a side effect of our glog wrapper. glog is an object when you use the wrapper and a package when you are not. 
So when we are using the wrapper, glog.Info in
```dockerpkg.StreamContainerIO(errReader, nil, glog.Info)```
actually requires the creation of a closure. Go does this invisibly for us, but the result is apparently then shared by anyone needing an identical closure. The first module to create the closure winds up in the stack (which explains why when you commented things out, the file/line was changing).

In the example below, postexecutorstep.go:328 creates it -- which results in the seemingly nonsensical stack.
```
goroutine 55 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x80
github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).writeln(0xc82000e260, 0x0, 0xc820380b70, 0x26)
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:135 +0x27f
github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).output(0xc82000e260, 0x0, 0xc82045e320, 0x1, 0x1)
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:156 +0x69
github.com/openshift/source-to-image/pkg/util/glog.(*FileLogger).Info(0xc82000e260, 0xc82045e320, 0x1, 0x1)
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/util/glog/glog.go:166 +0x47
github.com/openshift/source-to-image/pkg/util/glog.(Logger).Info-fm(0xc82045e320, 0x1, 0x1)
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/postexecutorstep.go:328 +0x50
github.com/openshift/source-to-image/pkg/docker.StreamContainerIO(0x7f61879ee818, 0xc8200901f0, 0xc820247740, 0xc82026fc60)
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/docker/util.go:97 +0x4de
created by github.com/openshift/source-to-image/pkg/build/strategies/sti.(*STI).Execute
        /home/jupierce/go/src/github.com/openshift/source-to-image/_output/local/go/src/github.com/openshift/source-to-image/pkg/build/strategies/sti/sti.go:593 +0x120e
```
This is likely an optimization on go's part since the closure can be reused safely/efficiently, but I've opened an issue for their awareness.

We can improve our log output by creating the closures ourselves. 
```dockerpkg.StreamContainerIO(errReader, nil, func(a ...interface{}){ glog.Info(a...) })```

**Closed** 2016-08-11 15:30 UTC
Labels: kind/bug, priority/P2

**Comment by jupierce** [comment] 2016-08-15 13:27
Confirmed with gloang issue that the optimization is to prevent binary code bloat.

**Comment by bparees** [comment] 2016-08-15 13:40
@jupierce do they consider this a bug or acceptable behavior?  I suppose the scenarios in which it impacts people are pretty rare, but i bet it confuses debuggers too.

**Comment by jupierce** [comment] 2016-08-15 17:44
They consider it an acceptable tradeoff : not ideal, but not something that cannot be addressed efficiently right now.

**Comment by bparees** [comment] 2016-08-15 18:14
fair enough.  great find, regardless.
