### ISSUE TITLE
Using a Docker TCP Socket with TLS fails

### ISSUE THREAD

**Issue by jasinner** [openshift/source-to-image#604] opened 2016-10-07 06:01 UTC
After upgrading from 1.0.9 to 1.1.2 s2i stopped working with Docker TCP Socket with TLS. I got it working on 1.0.9 by following the instructions here:  https://jasonshepherd.net/2016/09/21/using-openshift-container-platform-s2i-with-a-tcp-docker-daemon/

However after upgrading, the introduction of k8 dockertools library prevents it working again.

**Comment by bparees** [comment] 2016-10-09 23:45
I suspect this is a dupe of https://github.com/openshift/source-to-image/issues/603, can you tell us more about your environment?

**Comment by jasinner** [comment] 2016-10-10 00:54
Jasons-MacBook-Pro-3:jboss-dependency-viewer jasonshepherd$ s2i version
s2i v1.1.2
Jasons-MacBook-Pro-3:jboss-dependency-viewer jasonshepherd$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.0.1:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/jasonshepherd/.docker/
Jasons-MacBook-Pro-3:jboss-dependency-viewer jasonshepherd$ s2i build --loglevel=5 . jboss-eap-7/eap70-openshift jboss-dependecy-viewer
I1010 10:52:06.812003   97743 main.go:68] Running S2I version "v1.1.2"
I1010 10:52:06.816216   97743 docker.go:306] Connecting to docker on tcp://192.168.0.1:2376
I1010 10:52:06.836192   97743 docker.go:559] error inspecting image jboss-eap-7/eap70-openshift:latest: Get http://192.168.0.1:2376/images/jboss-eap-7/eap70-openshift:latest/json?size=1: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
I1010 10:52:06.852941   97743 docker.go:517] error inspecting image jboss-eap-7/eap70-openshift:latest: Get http://192.168.0.1:2376/images/jboss-eap-7/eap70-openshift:latest/json?size=1: malformed HTTP response "\x15\x03\x01\x00\x02\x02".
* Are you trying to connect to a TLS-enabled daemon without TLS?
I1010 10:52:06.853117   97743 main.go:147] 
Error describing image:		unable to get metadata for jboss-eap-7/eap70-openshift:latest
Source:				.
Output Image Tag:		jboss-dependecy-viewer
Environment:			
Incremental Build:		disabled
Remove Old Build:		disabled
Builder Pull Policy:		if-not-present
Previous Image Pull Policy:	if-not-present
Quiet:				disabled
Layered Build:			disabled
Docker Endpoint:		tcp://192.168.0.1:2376

I1010 10:52:06.856199   97743 docker.go:306] Connecting to docker on tcp://192.168.0.1:2376
F1010 10:52:06.856300   97743 main.go:150] Unable to connect to Docker daemon. Please set the DOCKER_HOST or make sure the Docker socket "tcp://192.168.0.1:2376" exists

**Comment by jasinner** [comment] 2016-10-10 01:00
Same thing also occurs on Fedora 24 with the same configuration.

**Comment by jim-minter** [comment] 2016-10-20 20:45
Hi @jasinner a patch that should fix this is now merged, if you can test against HEAD I'd be interested to know if it resolves your issue.

**Closed** 2016-11-30 15:46 UTC
